/* @flow */

export const SPENDER_TYPE = 'SPENDER_TYPE';
export const COMPLETED_DAY = 'COMPLETED_DAY';
export const SUBSCRIBE_FLOOZ_35_15 = 'SUBSCRIBE_FLOOZ_35_15';
export const SUBSCRIBE_FLOOZ_120_15 = 'SUBSCRIBE_FLOOZ_120_15';
export const BUY_FLOOZ_5USD = 'BUY_FLOOZ_5USD';
export const BUY_FLOOZ_10USD = 'BUY_FLOOZ_10USD';
export const BUY_FLOOZ_20USD = 'BUY_FLOOZ_20USD';
export const BUY_FLOOZ_50USD = 'BUY_FLOOZ_50USD';
export const BUY_FLOOZ_100USD = 'BUY_FLOOZ_100USD';
export const BUY_STARTER_PACK_WATER = 'BUY_STARTER_PACK_WATER';
export const BUY_STARTER_PACK_FIRE = 'BUY_STARTER_PACK_FIRE';
export const BUY_STARTER_PACK_EARTH = 'BUY_STARTER_PACK_EARTH';
export const BUY_STARTER_PACK_LIGHT = 'BUY_STARTER_PACK_LIGHT';
export const BUY_STARTER_PACK_DARK = 'BUY_STARTER_PACK_DARK';
export const OPEN_FORTUNE_CHEST = 'OPEN_FORTUNE_CHEST';
export const OPEN_PREMIUM_CHEST = 'OPEN_PREMIUM_CHEST';
export const OPEN_BLITZ_CHEST = 'OPEN_BLITZ_CHEST';
export const SET_DESIRED_HERO_EVOLUTION = 'SET_DESIRED_HERO_EVOLUTION';
export const NEXT_DAY = 'NEXT_DAY';
export const SET_TEAM = 'SET_TEAM';