/* @flow */

export const RARITY = {
  COMMON: "COMMON",
  RARE: "RARE",
  EPIC: "EPIC",
  // LEGENDARY: 'LEGENDARY'
};
export const REQUIRED_MEDALS = [10, 20, 50, 200, 600, 1500, 2500];
export const REQUIRED_TOTAL_MEDALS = REQUIRED_MEDALS.reduce((a, v, i) => {
  a.push(REQUIRED_MEDALS[i] + (a[i - 1] || 0));
  return a;
}, []);

export const ALL_RARITIES_LIST = [
  RARITY.COMMON,
  RARITY.RARE,
  RARITY.EPIC /* , RARITY.LEGENDARY */,
];

export const FIRST_DAY_GAME_DATE = "Mon, 04 May 2020 00:00:00 GMT";

export const SP1_TYPES = {
  NORMAL: "NORMAL",
  FREEZE_2SEC_30PRC: "FREEZE_2SEC_30PRC",
  FREEZE_2SEC_10PRC: "FREEZE_2SEC_10PRC",
  FREEZE_2SEC_5PRC: "FREEZE_2SEC_5PRC",
  AOE_100: "AOE_100",
  BURN_30_PRC_5SEC: "BURN_30_PRC_5SEC", // burns 60% of atk
  BURN_10_PRC_5SEC: "BURN_10_PRC_5SEC",
  POISON_20_PRC_5SEC: "POISON_20_PRC_5SEC", // 120% of base atack
  POISON_10_PRC_5SEC: "POISON_10_PRC_5SEC", // 120% of base atack
  POISON_30_PRC_5SEC_100_AOE: "POISON_30_PRC_5SEC_100_AOE",
  STUN_10_PRC_2_SEC: "STUN_10_PRC_2_SEC",
  STUN_20_PRC_CHANCE_3_SEC: "STUN_20_PRC_CHANCE_3_SEC",
  VAMPIRIC: "VAMPIRIC",
  TRIKSTER_MAGIC_CARD: "TRIKSTER_MAGIC_CARD",
};

export const SP2_TYPES = {
  NORMAL_X3: "NORMAL_X3",
  FREEZE_2SEC_10PRC: "FREEZE_2SEC_10PRC",
  AOE_150: "AOE_150",
  AOE_150_X3: "AOE_150_X3",
  AOE_350: "AOE_350",
  AOE_300: "AOE_300",
  AOE_300_X7: "AOE_300_X7",
  PUSH4: "PUSH4",
  PUSH10: "PUSH10",
  DEF_DOWN_50_PRC_6_SEC: "DEF_DOWN_50_PRC_6_SEC",
  NAMIDA_MISSLES: "NAMIDA_MISSLES",
  FREEZE_2SEC_10PRC_AOE_150: "FREEZE_2SEC_10PRC_AOE_150",
  BURN_10_PRC_5SEC: "BURN_10_PRC_5SEC",
  BURN_30_PRC_5SEC: "BURN_30_PRC_5SEC",
  BURN_5_PRC_5SEC: "BURN_5_PRC_5SEC",
  STUN_2_SEC_600_AOE: "STUN_2_SEC_600_AOE",
  BURN_5SEC_100_PRC_CHANCE_400_AOE: "BURN_5SEC_100_PRC_CHANCE_400_AOE",
  POISON_10_PRC_5SEC: "POISON_10_PRC_5SEC",
  POISON_20_PRC_5SEC: "POISON_20_PRC_5SEC",
  POISON_30_PRC_5_SEC_440_AOE: "POISON_30_PRC_5_SEC_440_AOE",
  SLOWDOWN_70_PRC_GROOVE: "SLOWDOWN_70_PRC_GROOVE",
  POISON_30_PRC_5SEC_150_AOE: "POISON_30_PRC_5SEC_150_AOE",
  PIERCING_BURN_100_PRC_3SEC: "PIERCING_BURN_100_PRC_3SEC",
  POISON_100_PRC_600_AOE: "POISON_100_PRC_600_AOE",
  SHIELD_5_PRC_OF_HEALTH: "SHIELD_5_PRC_OF_HEALTH",
  FROGIFY: "FROGIFY",
  HEALING_6_PRC_OF_CASTERS_LIFE_FOR_5_SEC:
    "HEALING_6_PRC_OF_CASTERS_LIFE_FOR_5_SEC",
  STUN_30_PRC_350_AOE: "STUN_30_PRC_350_AOE",
  BLIND_70_PRC_150_AOE_3_SEC: "BLIND_70_PRC_150_AOE_3_SEC",
  HEAL_100_PRC_CASTER_LIFE: "HEAL_100_PRC_CASTER_LIFE",
  STUN_2_SEC_ATK_DOWN_10_PRC_400_AOE: "STUN_2_SEC_ATK_DOWN_10_PRC_400_AOE",
  THOR_RUSH: "THOR_RUSH",
  STUN_3_SEC_150_AOE: "STUN_3_SEC_150_AOE",
  ANGEL_BARRIER: "ANGEL_BARRIER",
  ATK_DOWN_20_PRC_5_SEC: "ATK_DOWN_20_PRC_5_SEC",
  SORROW_FATAL_WEAKNESS: "SORROW_FATAL_WEAKNESS",
  CIRCE_POSSESS: "CIRCE_POSSESS",
  VLAD_BLOOD_LUST: "VLAD_BLOOD_LUST",
  NECROMANCER_SPAWN_SKELETON: "NECROMANCER_SPAWN_SKELETON",
  KASUMI_ASSASINATION: "KASUMI_ASSASINATION",
  TRIKSTER_CARDS_CASCADE: "TRIKSTER_CARDS_CASCADE",
};

export const SP4_TYPES = {
  ELEMENT_HP_400: "ELEMENT_HP_400",
  ELEMENT_HP_500: "ELEMENT_HP_500",
  ALL_HP_400: "ALL_HP_400",
  SELF_HP_800: "SELF_HP_800",

  DEBUFF_HP_25_PRC: "DEBUFF_HP_25_PRC",

  ELEMENT_DEF_400: "ELEMENT_DEF_400",
  ALL_DEF_400: "ALL_DEF_400",
  ALL_DEF_500: "ALL_DEF_500",

  DEBUFF_DEF_50_PRC: "DEBUFF_DEF_50_PRC",

  FREEZE_DURATION_4PRC: "FREEZE_DURATION_4PRC",
  ELEMENT_ATK_400: "ELEMENT_ATK_400",
  ALL_ATK_400: "ALL_ATK_400",
  ELEMENT_MOVE_SPEED_25: "ELEMENT_MOVE_SPEED_25",
  ALL_MOVE_SPEED_25: "ALL_MOVE_SPEED_25",
  ELEMENT_ATK_SPD_10: "ELEMENT_ATK_SPD_10",
  ELEMENT_CRT_DMG_200: "ELEMENT_CRT_DMG_200",
  ALL_CRT_DMG_300: "ALL_CRT_DMG_300",
  DEBUF_ELEMENT_DMG_200: "DEBUF_ELEMENT_DMG_200",
  FREEZE_EXPLODE_DMG_100: "FREEZE_EXPLODE_DMG_100",
  FRENZY_3_PRC: "FRENZY_3_PRC",
  POISON_DMG_50_PRC: "POISON_DMG_50_PRC",
  ROUGE_150_ALL_STATS: "ROUGE_150_ALL_STATS",
  ELEMENT_ATACK_RANGE_3_PRC: "ELEMENT_ATACK_RANGE_3_PRC",
  ELEMENT_2_PRC_DODGE: "ELEMENT_2_PRC_DODGE",
  LANCER_3_PRC_RANGE: "LANCER_3_PRC_RANGE",
  MAGICIANS_150_ALL: "MAGICIANS_150_ALL",
  SELF_ATK_800: "SELF_ATK_800",
  DEBUFF_EFFECT_DURATION_MINUS_25_PRC: "DEBUFF_EFFECT_DURATION_MINUS_25_PRC",
  DEBUFF_MOVE_SPD_25_PRC: "DEBUFF_MOVE_SPD_25_PRC",
  GUNNER_ATK_400: "GUNNER_ATK_400",
  DEBUFF_ATK_50_PRC: "DEBUFF_ATK_50_PRC",
  DEBUFF_ATK_SPD_10_PRC: "DEBUFF_ATK_SPD_10_PRC",
  SKELETON_BUFF_150_PRC: "SKELETON_BUFF_150_PRC",
  DEBUFF_DURATION_PLUS_6_PRC: "DEBUFF_DURATION_PLUS_6_PRC",
};

export const SP5_TYPES = {
  SNOWMAN_ON_KILL: "SNOWMAN_ON_KILL",
  ANTI_STUN: "ANTI_STUN",
  FREEZE_EXPLODE: "FREEZE_EXPLODE",
  ANTI_BURN_AND_FREEZE: "ANTI_BURN_AND_FREEZE",
  TELLUS_BLOCK_DMG: "TELLUS_BLOCK_DMG",
  ANTI_PUSHBACK: "ANTI_PUSHBACK",
  LAST_HOPE: "LAST_HOPE",
  SPAWN_MUMMY_ON_DEATH: "SPAWN_MUMMY_ON_DEATH",
  EVADE_GUNNER_BULLETS: "EVADE_GUNNER_BULLETS",
};

export const BLITZ_DURATION_DAYS = 4;
export const MAX_DAY = 2000;

export  const ONE_TICK_MS = 25;

export const DISTANCE_BETWEEN_CRYSTALS = 1800;
export const TICKS_IN_ONE_SECOND = 1000 / ONE_TICK_MS;
export const PUSH_BACK_DISTANCE_PER_TICK = 250 / TICKS_IN_ONE_SECOND;
export const TIME_BETWEEN_HEROS_SPAWN_SECS = 1;
export const MAX_BATTLE_DURATION_TICKS = 60 * 3 * TICKS_IN_ONE_SECOND;


export const aPortalId = "a-portal";
export const dPortalId = "d-portal";


export const ARENA_JOB_ROTATION = [
  "lancer",
  "ranger",
  "magician",
  "gunner",
  "support",
  "barbarian",
  "samurai",
  "rogue",
  "brawler",
  "knight",
];
