/* @flow */

/* :: import type { HeroName, BlitzShopHeroName, EventHeroName ,CrusherHeroName, BlitzHeroName, CommonHeroName, FcRareHeroName, FcEpicHeroName, CLS, RuneType, RunePrimariy, RuneSecondary, HeroBaseRecord, Hero } from '../../../../server/types' */

import {
  RARITY,
  SP1_TYPES,
  SP2_TYPES,
  SP4_TYPES,
  SP5_TYPES,
} from "./constants.mjs";

const dpsBuildFlyer = {
  runes: ["D", "P", "R"],
  runePrimaries: ["A", "D", "D"],
  runeSecondaries: ["L", "R", "V", "G"],
};
const poorDpsBuildFlyer = {
  runes: ["D", "V", "D"],
  runePrimaries: ["V", "D", "G"],
  runeSecondaries: ["B", "U", "V", "G"],
};
const grimore /* :Array<HeroBaseRecord> */ = [
  {
    name: "Blue Fish",
    elementKind: "water",
    tribe: "Dragon",
    sex: "f",
    flying: true,
    crusher: false,
    rarity: RARITY.COMMON,
    class: "magician",
    atk: 32,
    hp: 310,
    def: 8,
    ctkrate: 15,
    ctkdmg: 100,
    aps: 1,
    atkrange: 350,
    mvspd: 250,
    effresistance: 22,
    sp1: SP1_TYPES.NORMAL,
    sp2: SP2_TYPES.NORMAL_X3,
    runeBuilds: {
      default: dpsBuildFlyer,
      poor: poorDpsBuildFlyer,
    },
  },
  {
    name: "Bugonaut Archer",
    elementKind: "water",
    tribe: "Bugonaut",
    sex: "m",
    flying: false,
    crusher: false,
    rarity: RARITY.COMMON,
    class: "ranger",
    atk: 28,
    hp: 200,
    def: 15,
    ctkrate: 10,
    ctkdmg: 100,
    aps: 1,
    atkrange: 424,
    mvspd: 160,
    effresistance: 10,
    sp1: SP1_TYPES.NORMAL,
    sp2: SP2_TYPES.NORMAL_X3,
    runeBuilds: {
      default: {
        runes: ["D", "P", "R"],
        runePrimaries: ["A", "D", "D"],
        runeSecondaries: ["L", "R", "V", "G"],
      },
    },
  },
  {
    name: "Bugonaut Fighter",
    elementKind: "water",
    tribe: "Bugonaut",
    sex: "m",
    flying: false,
    crusher: false,
    rarity: RARITY.COMMON,
    class: "rogue",
    atk: 30,
    hp: 240,
    def: 15,
    ctkrate: 10,
    ctkdmg: 100,
    aps: 0.67,
    atkrange: 120,
    mvspd: 150,
    effresistance: 10,
    dodgerate: 10,
    sp1: SP1_TYPES.NORMAL,
    sp2: SP2_TYPES.NORMAL_X3,
    runeBuilds: {
      default: {
        runes: ["N", "P", "A"],
        runePrimaries: ["D", "D", "D"],
        runeSecondaries: ["L", "R", "V", "G"],
      },
    },
  },
  {
    name: "Bugonaut Spear",
    elementKind: "water",
    tribe: "Bugonaut",
    sex: "m",
    flying: false,
    crusher: false,
    rarity: RARITY.COMMON,
    class: "lancer",
    atk: 28,
    hp: 280,
    def: 15,
    ctkrate: 10,
    ctkdmg: 100,
    aps: 0.4,
    atkrange: 220,
    mvspd: 110,
    effresistance: 10,

    sp1: SP1_TYPES.NORMAL,
    sp2: SP2_TYPES.NORMAL_X3,
    runeBuilds: {
      default: {
        runes: ["V", "X", "D"],
        runePrimaries: ["A", "A", "A"],
        runeSecondaries: ["L", "D", "V", "R"],
      },
    },
  },
  {
    name: "Bugonaut Giant",
    elementKind: "water",
    tribe: "Bugonaut",
    sex: "m",
    flying: false,
    crusher: false,
    rarity: RARITY.COMMON,
    class: "barbarian",
    atk: 35,
    hp: 400,
    def: 20,
    ctkrate: 20,
    ctkdmg: 100,
    aps: 0.5,
    atkrange: 220,
    mvspd: 100,
    effresistance: 6,
    sp1: SP1_TYPES.NORMAL,
    sp2: SP2_TYPES.AOE_150_X3,
    runeBuilds: {
      default: {
        runes: ["V", "N", "G"],
        runePrimaries: ["V", "V", "V"],
        runeSecondaries: ["M", "G", "D", "R"],
      },
    },
  },
  {
    name: "Ice Knight",
    elementKind: "water",
    tribe: "Human",
    sex: "m",
    flying: false,
    crusher: false,
    rarity: RARITY.COMMON,
    class: "knight",
    atk: 48,
    hp: 300,
    def: 15,
    ctkrate: 10,
    ctkdmg: 100,
    aps: 1,
    atkrange: 150,
    mvspd: 135,
    effresistance: 25,
    sp1: SP1_TYPES.FREEZE_2SEC_10PRC,
    sp2: SP2_TYPES.FREEZE_2SEC_10PRC,
    sp4: SP4_TYPES.FREEZE_DURATION_4PRC,
    runeBuilds: {
      default: {
        runes: ["V", "K", "N"],
        runePrimaries: ["V", "V", "V"],
        runeSecondaries: ["M", "G", "D", "R"],
      },
    },
  },
  {
    name: "Pirato",
    elementKind: "water",
    tribe: "Monki",
    sex: "m",
    flying: false,
    crusher: false,
    rarity: RARITY.RARE,
    class: "gunner",
    atk: 28,
    hp: 200,
    def: 6,
    ctkrate: 10,
    ctkdmg: 100,
    aps: 0.83,
    atkrange: 408,
    mvspd: 180,
    effresistance: 10,
    sp1: SP1_TYPES.AOE_100,
    sp2: SP2_TYPES.AOE_150,
    sp4: SP4_TYPES.ELEMENT_ATK_400,
    runeBuilds: {
      default: {
        runes: ["D", "A", "C"],
        runePrimaries: ["E", "E", "D"],
        runeSecondaries: ["D", "L", "R", "V"],
      },
    },
  },
  {
    name: "Rufus",
    elementKind: "water",
    tribe: "Human",
    sex: "m",
    flying: false,
    crusher: false,
    rarity: RARITY.RARE,
    class: "gunner",
    atk: 40,
    hp: 240,
    def: 10,
    ctkrate: 15,
    ctkdmg: 200,
    aps: 0.83,
    atkrange: 430,
    mvspd: 160,
    effresistance: 6,
    sp1: SP1_TYPES.NORMAL,
    sp2: SP2_TYPES.NORMAL_X3,
    sp4: SP4_TYPES.ELEMENT_DEF_400,
    runeBuilds: {
      default: {
        runes: ["D", "P", "R"],
        runePrimaries: ["A", "D", "D"],
        runeSecondaries: ["L", "R", "V", "G"],
      },
    },
  },
  {
    name: "Oceana",
    elementKind: "water",
    tribe: "Human",
    sex: "f",
    flying: false,
    crusher: false,
    rarity: RARITY.RARE,
    class: "magician",
    atk: 40,
    hp: 360,
    def: 8,
    ctkrate: 10,
    ctkdmg: 100,
    aps: 0.67,
    atkrange: 520,
    mvspd: 160,
    effresistance: 20,
    sp1: SP1_TYPES.NORMAL,
    sp2: SP2_TYPES.NORMAL_X3,
    sp4: SP4_TYPES.ELEMENT_DEF_400,
    runeBuilds: {
      default: {
        runes: ["D", "P", "R"],
        runePrimaries: ["A", "D", "D"],
        runeSecondaries: ["L", "R", "V", "G"],
      },
    },
  },
  {
    name: "Goddess",
    elementKind: "water",
    tribe: "Bugonaut",
    sex: "f",
    flying: false,
    crusher: false,
    rarity: RARITY.RARE,
    class: "support",
    atk: 14,
    hp: 200,
    def: 10,
    ctkrate: 10,
    ctkdmg: 100,
    aps: 0.5,
    atkrange: 520,
    mvspd: 140,
    effresistance: 26,
    sp1: SP1_TYPES.NORMAL,
    sp2: SP2_TYPES.PUSH10,
    sp4: SP4_TYPES.ELEMENT_HP_400,
    runeBuilds: {
      default: {
        runes: ["A", "C", "X"],
        runePrimaries: ["A", "A", "A"],
        runeSecondaries: ["L", "D", "R", "V"],
      },
    },
  },
  {
    name: "Snowman",
    elementKind: "water",
    tribe: "Human",
    sex: "m",
    flying: false,
    crusher: false,
    rarity: RARITY.RARE,
    class: "ranger",
    atk: 30,
    hp: 280,
    def: 11,
    ctkrate: 15,
    ctkdmg: 100,
    aps: 1,
    atkrange: 440,
    mvspd: 140,
    effresistance: 15,
    sp1: SP1_TYPES.NORMAL,
    sp2: SP2_TYPES.DEF_DOWN_50_PRC_6_SEC,
    sp4: SP4_TYPES.ELEMENT_ATK_400,
    sp5: SP5_TYPES.SNOWMAN_ON_KILL,
    runeBuilds: {
      default: {
        runes: ["A", "C", "X"],
        runePrimaries: ["A", "A", "A"],
        runeSecondaries: ["L", "D", "R", "V"],
      },
    },
  },
  {
    name: "Black Beard",
    elementKind: "water",
    tribe: "Human",
    sex: "m",
    flying: false,
    crusher: false,
    rarity: RARITY.RARE,
    class: "knight",
    atk: 45,
    hp: 360,
    def: 12,
    ctkrate: 15,
    ctkdmg: 100,
    aps: 1,
    atkrange: 150,
    mvspd: 160,
    effresistance: 10,
    sp1: SP1_TYPES.NORMAL,
    sp2: SP2_TYPES.NORMAL_X3,
    sp4: SP4_TYPES.ELEMENT_DEF_400,
    runeBuilds: {
      default: {
        runes: ["V", "K", "N"],
        runePrimaries: ["V", "V", "V"],
        runeSecondaries: ["M", "G", "D", "R"],
      },
    },
  },
  {
    name: "Luka",
    elementKind: "water",
    tribe: "Human",
    sex: "m",
    flying: false,
    crusher: false,
    rarity: RARITY.RARE,
    class: "rogue",
    atk: 37,
    hp: 240,
    def: 8,
    ctkrate: 10,
    ctkdmg: 100,
    aps: 1,
    atkrange: 120,
    mvspd: 220,
    effresistance: 15,
    dodgerate: 10,
    sp1: SP1_TYPES.NORMAL,
    sp2: SP2_TYPES.NORMAL_X3,
    sp4: SP4_TYPES.ELEMENT_MOVE_SPEED_25,
    runeBuilds: {
      default: {
        runes: ["N", "P", "A"],
        runePrimaries: ["D", "D", "D"],
        runeSecondaries: ["L", "R", "V", "G"],
      },
    },
  },
  {
    name: "Mizu",
    elementKind: "water",
    tribe: "Human",
    sex: "m",
    flying: false,
    crusher: false,
    rarity: RARITY.RARE,
    class: "samurai",
    atk: 56,
    hp: 260,
    def: 8,
    ctkrate: 20,
    ctkdmg: 200,
    aps: 1,
    atkrange: 150,
    mvspd: 170,
    effresistance: 6,
    sp1: SP1_TYPES.NORMAL,
    sp2: SP2_TYPES.NORMAL_X3,
    sp4: SP4_TYPES.ELEMENT_ATK_400,
    runeBuilds: {
      default: {
        runes: ["N", "P", "A"],
        runePrimaries: ["D", "D", "D"],
        runeSecondaries: ["L", "R", "V", "G"],
      },
    },
  },
  {
    name: "Akwa",
    elementKind: "water",
    tribe: "Human",
    sex: "f",
    flying: false,
    crusher: false,
    rarity: RARITY.RARE,
    class: "brawler",
    atk: 48,
    hp: 360,
    def: 20,
    ctkrate: 20,
    ctkdmg: 100,
    aps: 1,
    atkrange: 200,
    mvspd: 140,
    effresistance: 24,
    sp1: SP1_TYPES.NORMAL,
    sp2: SP2_TYPES.PUSH4,
    sp4: SP4_TYPES.ELEMENT_ATK_SPD_10,
    runeBuilds: {
      default: {
        runes: ["V", "A", "C"],
        runePrimaries: ["D", "D", "D"],
        runeSecondaries: ["L", "R", "V", "G"],
      },
    },
  },
  {
    name: "Atlantus",
    elementKind: "water",
    tribe: "Human",
    sex: "m",
    flying: false,
    crusher: true,
    rarity: RARITY.RARE,
    class: "lancer",
    atk: 40,
    hp: 430,
    def: 12,
    ctkrate: 20,
    ctkdmg: 100,
    aps: 0.4,
    atkrange: 220,
    mvspd: 140,
    effresistance: 15,

    sp1: SP1_TYPES.NORMAL,
    sp2: SP2_TYPES.AOE_350,
    sp4: SP4_TYPES.ELEMENT_CRT_DMG_200,
    sp5: SP5_TYPES.ANTI_STUN,
    runeBuilds: {
      default: {
        runes: ["V", "D", "P"],
        runePrimaries: ["A", "A", "A"],
        runeSecondaries: ["D", "L", "R", "V"],
      },
    },
  },
  {
    name: "Namida",
    elementKind: "water",
    tribe: "Human",
    sex: "f",
    flying: true,
    crusher: false,
    rarity: RARITY.EPIC,
    class: "gunner",
    atk: 25,
    hp: 320,
    def: 6,
    ctkrate: 15,
    ctkdmg: 100,
    aps: 0.83,
    atkrange: 415,
    mvspd: 160,
    effresistance: 8,
    sp1: SP1_TYPES.AOE_100,
    sp2: SP2_TYPES.NAMIDA_MISSLES,
    sp4: SP4_TYPES.DEBUF_ELEMENT_DMG_200,
    runeBuilds: {
      default: {
        runes: ["A", "C", "X"],
        runePrimaries: ["A", "A", "E"],
        runeSecondaries: ["L", "D", "R", "V"],
      },
    },
  },
  {
    name: "Valkyrie",
    elementKind: "water",
    tribe: "Human",
    sex: "f",
    flying: false,
    crusher: false,
    rarity: RARITY.EPIC,
    class: "ranger",
    atk: 32,
    hp: 280,
    def: 12,
    ctkrate: 20,
    ctkdmg: 100,
    aps: 1,
    atkrange: 550,
    mvspd: 150,
    effresistance: 8,
    sp1: SP1_TYPES.FREEZE_2SEC_5PRC,
    sp2: SP2_TYPES.FREEZE_2SEC_10PRC,
    sp4: SP4_TYPES.ALL_CRT_DMG_300,
    runeBuilds: {
      default: {
        runes: ["D", "P", "C"],
        runePrimaries: ["A", "D", "D"],
        runeSecondaries: ["L", "R", "V", "G"],
      },
    },
  },
  {
    name: "Frost Queen",
    elementKind: "water",
    tribe: "Human",
    sex: "f",
    flying: false,
    crusher: false,
    rarity: RARITY.EPIC,
    class: "magician",
    atk: 28,
    hp: 280,
    def: 12,
    ctkrate: 20,
    ctkdmg: 100,
    aps: 1,
    atkrange: 520,
    mvspd: 150,
    effresistance: 8,
    sp1: SP1_TYPES.FREEZE_2SEC_30PRC,
    sp2: SP2_TYPES.FREEZE_2SEC_10PRC,
    sp4: SP4_TYPES.FREEZE_EXPLODE_DMG_100,
    sp5: SP5_TYPES.FREEZE_EXPLODE,
    runeBuilds: {
      default: {
        runes: ["F", "C", "E"],
        runePrimaries: ["A", "A", "A"],
        runeSecondaries: ["L", "D", "R", "V"],
      },
    },
  },
  {
    name: "Ice Cube",
    elementKind: "water",
    tribe: "?",
    sex: "m",
    flying: false,
    crusher: false,
    rarity: RARITY.EPIC,
    class: "barbarian",
    atk: 45,
    hp: 580,
    def: 14,
    ctkrate: 10,
    ctkdmg: 100,
    aps: 0.83,
    atkrange: 150,
    mvspd: 100,
    effresistance: 10,
    sp1: SP1_TYPES.FREEZE_2SEC_10PRC,
    sp2: SP2_TYPES.FREEZE_2SEC_10PRC_AOE_150,
    sp4: SP4_TYPES.ALL_DEF_400,
    runeBuilds: {
      default: {
        runes: ["V", "N", "G"],
        runePrimaries: ["V", "V", "V"],
        runeSecondaries: ["M", "G", "D", "R"],
      },
    },
  },
  {
    name: "Vulcan Archer",
    elementKind: "fire",
    tribe: "Vulcan",
    sex: "m",
    flying: false,
    crusher: false,
    rarity: RARITY.COMMON,
    class: "ranger",
    atk: 24,
    hp: 200,
    def: 10,
    ctkrate: 15,
    ctkdmg: 100,
    aps: 1,
    atkrange: 380,
    mvspd: 150,
    effresistance: 8,
    sp1: SP1_TYPES.BURN_30_PRC_5SEC,
    sp2: SP2_TYPES.BURN_10_PRC_5SEC,
    runeBuilds: {
      default: {
        runes: ["D", "I", "B"],
        runePrimaries: ["A", "A", "A"],
        runeSecondaries: ["D", "L", "R", "V"],
      },
    },
  },
  {
    name: "Vulcan Fighter",
    elementKind: "fire",
    tribe: "Vulcan",
    sex: "m",
    flying: false,
    crusher: false,
    rarity: RARITY.COMMON,
    class: "rogue",
    atk: 30,
    hp: 240,
    def: 10,
    ctkrate: 15,
    ctkdmg: 100,
    aps: 1,
    atkrange: 120,
    mvspd: 150,
    effresistance: 6,
    dodgerate: 10,
    sp1: SP1_TYPES.NORMAL,
    sp2: SP2_TYPES.NORMAL_X3,
    runeBuilds: {
      default: {
        runes: ["N", "P", "A"],
        runePrimaries: ["D", "D", "D"],
        runeSecondaries: ["L", "R", "V", "G"],
      },
    },
  },
  {
    name: "Tiny Dragon",
    elementKind: "fire",
    tribe: "Dragon",
    sex: "m",
    flying: true,
    crusher: false,
    rarity: RARITY.COMMON,
    class: "magician",
    atk: 38,
    hp: 210,
    def: 8,
    ctkrate: 15,
    ctkdmg: 100,
    aps: 1,
    atkrange: 300,
    mvspd: 180,
    effresistance: 18,
    sp1: SP1_TYPES.BURN_10_PRC_5SEC,
    sp2: SP2_TYPES.BURN_5_PRC_5SEC,
    runeBuilds: {
      default: {
        runes: ["D", "P", "R"],
        runePrimaries: ["A", "D", "D"],
        runeSecondaries: ["L", "R", "V", "G"],
      },
    },
  },
  {
    name: "Vulcan Hammer",
    elementKind: "fire",
    tribe: "Vulcan",
    sex: "f",
    flying: false,
    crusher: false,
    rarity: RARITY.COMMON,
    class: "barbarian",
    atk: 45,
    hp: 400,
    def: 10,
    ctkrate: 15,
    ctkdmg: 100,
    aps: 0.5,
    atkrange: 130,
    mvspd: 110,
    effresistance: 10,
    sp1: SP1_TYPES.NORMAL,
    sp2: SP2_TYPES.AOE_150_X3,
    runeBuilds: {
      default: {
        runes: ["V", "N", "G"],
        runePrimaries: ["V", "V", "V"],
        runeSecondaries: ["M", "G", "D", "R"],
      },
    },
  },
  {
    name: "Monki King",
    elementKind: "fire",
    tribe: "Monki",
    sex: "m",
    flying: true,
    crusher: false,
    rarity: RARITY.RARE,
    class: "lancer",
    atk: 38,
    hp: 210,
    def: 8,
    ctkrate: 15,
    ctkdmg: 100,
    aps: 1,
    atkrange: 320,
    mvspd: 180,
    effresistance: 14,

    sp1: SP1_TYPES.NORMAL,
    sp2: SP2_TYPES.AOE_300_X7,
    sp4: SP4_TYPES.ELEMENT_ATK_SPD_10,
    runeBuilds: {
      default: {
        runes: ["X", "S", "E"],
        runePrimaries: ["E", "E", "E"],
        runeSecondaries: ["L", "D", "R", "V"],
      },
    },
  },
  {
    name: "Fire Monk",
    elementKind: "fire",
    tribe: "Human",
    sex: "m",
    flying: false,
    crusher: false,
    rarity: RARITY.RARE,
    class: "magician",
    atk: 45,
    hp: 320,
    def: 8,
    ctkrate: 10,
    ctkdmg: 100,
    aps: 0.67,
    atkrange: 450,
    mvspd: 160,
    effresistance: 16,
    sp1: SP1_TYPES.NORMAL,
    sp2: SP2_TYPES.NORMAL_X3,
    sp4: SP4_TYPES.ELEMENT_HP_400,
    runeBuilds: {
      default: {
        runes: ["D", "P", "R"],
        runePrimaries: ["A", "D", "D"],
        runeSecondaries: ["L", "R", "V", "G"],
      },
    },
  },
  {
    name: "Magmus",
    elementKind: "fire",
    tribe: "?",
    sex: "m",
    flying: false,
    crusher: false,
    rarity: RARITY.RARE,
    class: "barbarian",
    atk: 65,
    hp: 500,
    def: 18,
    ctkrate: 15,
    ctkdmg: 100,
    aps: 0.5,
    atkrange: 220,
    mvspd: 100,
    effresistance: 7,
    sp1: SP1_TYPES.NORMAL,
    sp2: SP2_TYPES.AOE_150_X3,
    sp4: SP4_TYPES.ELEMENT_DEF_400,
    runeBuilds: {
      default: {
        runes: ["V", "N", "G"],
        runePrimaries: ["V", "V", "V"],
        runeSecondaries: ["M", "G", "D", "R"],
      },
    },
  },
  {
    name: "Jasmine",
    elementKind: "fire",
    tribe: "Human",
    sex: "f",
    flying: false,
    crusher: false,
    rarity: RARITY.RARE,
    class: "rogue",
    atk: 45,
    hp: 240,
    def: 8,
    ctkrate: 30,
    ctkdmg: 100,
    aps: 1,
    atkrange: 150,
    mvspd: 200,
    effresistance: 6,
    dodgerate: 10,
    sp1: SP1_TYPES.NORMAL,
    sp2: SP2_TYPES.NORMAL_X3,
    sp4: SP4_TYPES.ELEMENT_CRT_DMG_200,
    runeBuilds: {
      default: {
        runes: ["N", "P", "A"],
        runePrimaries: ["D", "D", "D"],
        runeSecondaries: ["L", "R", "V", "G"],
      },
    },
  },
  {
    name: "Mecha Valken",
    elementKind: "fire",
    tribe: "Valken",
    sex: "m",
    flying: false,
    crusher: false,
    rarity: RARITY.RARE,
    class: "brawler",
    atk: 65,
    hp: 310,
    def: 20,
    ctkrate: 20,
    ctkdmg: 100,
    aps: 0.83,
    atkrange: 180,
    mvspd: 140,
    effresistance: 20,
    sp1: SP1_TYPES.NORMAL,
    sp2: SP2_TYPES.AOE_300,
    sp4: SP4_TYPES.ELEMENT_DEF_400,
    runeBuilds: {
      default: {
        runes: ["V", "D", "P"],
        runePrimaries: ["E", "E", "E"],
        runeSecondaries: ["L", "D", "R", "V"],
      },
    },
  },
  {
    name: "Furiosa",
    elementKind: "fire",
    tribe: "Human",
    sex: "f",
    flying: false,
    crusher: true,
    rarity: RARITY.RARE,
    class: "knight",
    atk: 60,
    hp: 340,
    def: 14,
    ctkrate: 20,
    ctkdmg: 100,
    aps: 1,
    atkrange: 150,
    mvspd: 150,
    effresistance: 8,
    sp1: SP1_TYPES.NORMAL,
    sp2: SP2_TYPES.NORMAL_X3,
    sp4: SP4_TYPES.FRENZY_3_PRC,
    sp5: SP5_TYPES.ANTI_BURN_AND_FREEZE,
    runeBuilds: {
      default: {
        runes: ["V", "K", "N"],
        runePrimaries: ["V", "V", "V"],
        runeSecondaries: ["M", "G", "D", "R"],
      },
    },
  },
  {
    name: "Kasai",
    elementKind: "fire",
    tribe: "Human",
    sex: "m",
    flying: false,
    crusher: false,
    rarity: RARITY.RARE,
    class: "samurai",
    atk: 62,
    hp: 220,
    def: 8,
    ctkrate: 30,
    ctkdmg: 200,
    aps: 1,
    atkrange: 150,
    mvspd: 170,
    effresistance: 4,
    sp1: SP1_TYPES.NORMAL,
    sp2: SP2_TYPES.NORMAL_X3,
    sp4: SP4_TYPES.ELEMENT_ATK_400,
    runeBuilds: {
      default: {
        runes: ["N", "P", "A"],
        runePrimaries: ["D", "D", "D"],
        runeSecondaries: ["L", "R", "V", "G"],
      },
    },
  },
  {
    name: "Spyro",
    elementKind: "fire",
    tribe: "Vulcan",
    sex: "m",
    flying: false,
    crusher: false,
    rarity: RARITY.RARE,
    class: "lancer",
    atk: 45,
    hp: 320,
    def: 12,
    ctkrate: 10,
    ctkdmg: 100,
    aps: 0.4,
    atkrange: 220,
    mvspd: 140,
    effresistance: 8,

    sp1: SP1_TYPES.NORMAL,
    sp2: SP2_TYPES.BURN_30_PRC_5SEC,
    sp4: SP4_TYPES.FRENZY_3_PRC,
    runeBuilds: {
      default: {
        runes: ["V", "X", "D"],
        runePrimaries: ["A", "A", "A"],
        runeSecondaries: ["L", "D", "V", "R"],
      },
    },
  },
  {
    name: "Xak",
    elementKind: "fire",
    tribe: "Vulcan",
    sex: "m",
    flying: false,
    crusher: false,
    rarity: RARITY.RARE,
    class: "support",
    atk: 20,
    hp: 180,
    def: 10,
    ctkrate: 10,
    ctkdmg: 100,
    aps: 0.67,
    atkrange: 420,
    mvspd: 170,
    effresistance: 22,
    sp1: SP1_TYPES.NORMAL,
    sp2: SP2_TYPES.STUN_2_SEC_600_AOE,
    sp4: SP4_TYPES.ELEMENT_MOVE_SPEED_25,
    runeBuilds: {
      default: {
        runes: ["A", "S", "E"],
        runePrimaries: ["A", "E", "E"],
        runeSecondaries: ["L", "D", "V", "R"],
      },
    },
  },
  {
    name: "Spark",
    elementKind: "fire",
    tribe: "Human",
    sex: "m",
    flying: false,
    crusher: false,
    rarity: RARITY.RARE,
    class: "ranger",
    atk: 36,
    hp: 250,
    def: 8,
    ctkrate: 25,
    ctkdmg: 100,
    aps: 1,
    atkrange: 505,
    mvspd: 170,
    effresistance: 6,
    sp1: SP1_TYPES.BURN_30_PRC_5SEC,
    sp2: SP2_TYPES.PIERCING_BURN_100_PRC_3SEC,
    sp4: SP4_TYPES.DEBUF_ELEMENT_DMG_200,
    runeBuilds: {
      default: {
        runes: ["D", "I", "B"],
        runePrimaries: ["A", "D", "D"],
        runeSecondaries: ["L", "R", "V", "G"],
      },
    },
  },
  {
    name: "Scud",
    elementKind: "fire",
    tribe: "Human",
    sex: "m",
    flying: false,
    crusher: false,
    rarity: RARITY.EPIC,
    class: "gunner",
    atk: 35,
    hp: 210,
    def: 8,
    ctkrate: 15,
    ctkdmg: 100,
    aps: 0.83,
    atkrange: 400,
    mvspd: 160,
    effresistance: 10,
    sp1: SP1_TYPES.AOE_100,
    sp2: SP2_TYPES.AOE_150,
    sp4: SP4_TYPES.ALL_ATK_400,
    runeBuilds: {
      default: {
        runes: ["D", "A", "P"],
        runePrimaries: ["D", "D", "D"],
        runeSecondaries: ["L", "R", "V", "G"],
      },
    },
  },
  {
    name: "Torch",
    elementKind: "fire",
    tribe: "Vulcan",
    sex: "m",
    flying: false,
    crusher: false,
    rarity: RARITY.EPIC,
    class: "gunner",
    atk: 40,
    hp: 220,
    def: 10,
    ctkrate: 10,
    ctkdmg: 100,
    aps: 0.71,
    atkrange: 345,
    mvspd: 125,
    effresistance: 10,
    sp1: SP1_TYPES.NORMAL,
    sp2: SP2_TYPES.BURN_5SEC_100_PRC_CHANCE_400_AOE,
    sp4: SP4_TYPES.ALL_ATK_400,
    runeBuilds: {
      default: {
        runes: ["D", "B", "A"],
        runePrimaries: ["D", "D", "D"],
        runeSecondaries: ["L", "R", "V", "G"],
      },
    },
  },
  {
    name: "Alda",
    elementKind: "fire",
    tribe: "Human",
    sex: "f",
    flying: false,
    crusher: false,
    rarity: RARITY.EPIC,
    class: "ranger",
    atk: 38,
    hp: 240,
    def: 6,
    ctkrate: 25,
    ctkdmg: 100,
    aps: 1,
    atkrange: 555,
    mvspd: 150,
    effresistance: 6,
    sp1: SP1_TYPES.BURN_30_PRC_5SEC,
    sp2: SP2_TYPES.BURN_10_PRC_5SEC,
    sp4: SP4_TYPES.ALL_CRT_DMG_300,
    runeBuilds: {
      default: {
        runes: ["D", "P", "R"],
        runePrimaries: ["A", "D", "D"],
        runeSecondaries: ["L", "R", "V", "G"],
      },
    },
  },
  {
    name: "Voodoo Spear",
    elementKind: "earth",
    tribe: "Voodoo",
    sex: "f",
    flying: false,
    crusher: false,
    rarity: RARITY.COMMON,
    class: "lancer",
    atk: 32,
    hp: 320,
    def: 6,
    ctkrate: 15,
    ctkdmg: 100,
    aps: 0.4,
    atkrange: 220,
    mvspd: 160,
    effresistance: 10,
    sp1: SP1_TYPES.POISON_20_PRC_5SEC,
    sp2: SP2_TYPES.NORMAL_X3,
    runeBuilds: {
      default: {
        runes: ["V", "X", "D"],
        runePrimaries: ["A", "A", "A"],
        runeSecondaries: ["L", "D", "V", "R"],
      },
    },
  },
  {
    name: "Sprout",
    elementKind: "earth",
    tribe: "Dragon",
    sex: "m",
    flying: true,
    crusher: false,
    rarity: RARITY.COMMON,
    class: "magician",
    atk: 34,
    hp: 260,
    def: 8,
    ctkrate: 15,
    ctkdmg: 100,
    aps: 1,
    atkrange: 370,
    mvspd: 180,
    effresistance: 22,
    sp1: SP1_TYPES.NORMAL,
    sp2: SP2_TYPES.NORMAL_X3,
    runeBuilds: {
      default: {
        runes: ["D", "P", "R"],
        runePrimaries: ["A", "D", "D"],
        runeSecondaries: ["L", "R", "V", "G"],
      },
    },
  },
  {
    name: "Voodoo Archer",
    elementKind: "earth",
    tribe: "Voodoo",
    sex: "m",
    flying: false,
    crusher: false,
    rarity: RARITY.COMMON,
    class: "ranger",
    atk: 24,
    hp: 240,
    def: 6,
    ctkrate: 15,
    ctkdmg: 100,
    aps: 1,
    atkrange: 425,
    mvspd: 160,
    effresistance: 10,
    sp1: SP1_TYPES.POISON_20_PRC_5SEC,
    sp2: SP2_TYPES.POISON_10_PRC_5SEC,
    runeBuilds: {
      default: {
        runes: ["D", "P", "R"],
        runePrimaries: ["A", "D", "D"],
        runeSecondaries: ["L", "R", "V", "G"],
      },
    },
  },
  {
    name: "Voodoo Dagger",
    elementKind: "earth",
    tribe: "Voodoo",
    sex: "m",
    flying: false,
    crusher: false,
    rarity: RARITY.COMMON,
    class: "rogue",
    atk: 35,
    hp: 200,
    def: 8,
    ctkrate: 35,
    ctkdmg: 100,
    aps: 1,
    atkrange: 120,
    mvspd: 220,
    effresistance: 14,
    dodgerate: 10,
    sp1: SP1_TYPES.POISON_20_PRC_5SEC,
    sp2: SP2_TYPES.NORMAL_X3,
    runeBuilds: {
      default: {
        runes: ["N", "P", "A"],
        runePrimaries: ["D", "D", "D"],
        runeSecondaries: ["L", "R", "V", "G"],
      },
    },
  },
  {
    name: "Pumpking",
    elementKind: "earth",
    tribe: "Human",
    sex: "m",
    flying: false,
    crusher: false,
    rarity: RARITY.RARE,
    class: "barbarian",
    atk: 40,
    hp: 550,
    def: 20,
    ctkrate: 15,
    ctkdmg: 100,
    aps: 0.83,
    atkrange: 220,
    mvspd: 100,
    effresistance: 10,
    sp1: SP1_TYPES.POISON_10_PRC_5SEC,
    sp2: SP2_TYPES.POISON_30_PRC_5_SEC_440_AOE,
    sp4: SP4_TYPES.POISON_DMG_50_PRC,
    runeBuilds: {
      default: {
        runes: ["V", "N", "G"],
        runePrimaries: ["V", "V", "V"],
        runeSecondaries: ["M", "G", "D", "R"],
      },
    },
  },
  {
    name: "Groovine",
    elementKind: "earth",
    tribe: "Valken",
    sex: "f",
    flying: false,
    crusher: true,
    rarity: RARITY.RARE,
    class: "magician",
    atk: 48,
    hp: 350,
    def: 9,
    ctkrate: 10,
    ctkdmg: 100,
    aps: 1,
    atkrange: 550,
    mvspd: 140,
    effresistance: 24,
    sp1: SP1_TYPES.NORMAL,
    sp2: SP2_TYPES.SLOWDOWN_70_PRC_GROOVE,
    sp4: SP4_TYPES.ELEMENT_ATK_400,
    runeBuilds: {
      default: {
        runes: ["D", "Y", "W"],
        runePrimaries: ["D", "D", "D"],
        runeSecondaries: ["L", "R", "V", "G"],
      },
    },
    timedSp2Sec: 10,
  },
  {
    name: "Musashi",
    elementKind: "earth",
    tribe: "Human",
    sex: "m",
    flying: false,
    crusher: false,
    rarity: RARITY.RARE,
    class: "samurai",
    atk: 46,
    hp: 300,
    def: 8,
    ctkrate: 20,
    ctkdmg: 200,
    aps: 1,
    atkrange: 150,
    mvspd: 170,
    effresistance: 8,
    sp1: SP1_TYPES.NORMAL,
    sp2: SP2_TYPES.NORMAL_X3,
    sp4: SP4_TYPES.ALL_MOVE_SPEED_25,
    runeBuilds: {
      default: {
        runes: ["N", "P", "A"],
        runePrimaries: ["D", "D", "D"],
        runeSecondaries: ["L", "R", "V", "G"],
      },
    },
  },
  {
    name: "Robin Hood",
    elementKind: "earth",
    tribe: "Human",
    sex: "m",
    flying: false,
    crusher: false,
    rarity: RARITY.RARE,
    class: "ranger",
    atk: 30,
    hp: 270,
    def: 6,
    ctkrate: 25,
    ctkdmg: 100,
    aps: 1,
    atkrange: 590,
    mvspd: 160,
    effresistance: 8,
    sp1: SP1_TYPES.NORMAL,
    sp2: SP2_TYPES.NORMAL_X3,
    sp4: SP4_TYPES.ELEMENT_CRT_DMG_200,
    runeBuilds: {
      default: {
        runes: ["D", "P", "R"],
        runePrimaries: ["A", "D", "D"],
        runeSecondaries: ["L", "R", "V", "G"],
      },
    },
  },
  {
    name: "Gladiator",
    elementKind: "earth",
    tribe: "?",
    sex: "m",
    flying: false,
    crusher: false,
    rarity: RARITY.RARE,
    class: "barbarian",
    atk: 42,
    hp: 840,
    def: 25,
    ctkrate: 15,
    ctkdmg: 100,
    aps: 0.67,
    atkrange: 150,
    mvspd: 100,
    effresistance: 12,
    sp1: SP1_TYPES.NORMAL,
    sp2: SP2_TYPES.AOE_350,
    sp4: SP4_TYPES.ELEMENT_HP_400,
    runeBuilds: {
      default: {
        runes: ["V", "N", "G"],
        runePrimaries: ["V", "V", "V"],
        runeSecondaries: ["M", "G", "D", "R"],
      },
    },
  },
  {
    name: "Pinky",
    elementKind: "earth",
    tribe: "Human",
    sex: "m",
    flying: false,
    crusher: false,
    rarity: RARITY.RARE,
    class: "rogue",
    atk: 42,
    hp: 200,
    def: 12,
    ctkrate: 35,
    ctkdmg: 100,
    aps: 1,
    atkrange: 120,
    mvspd: 230,
    effresistance: 14,
    dodgerate: 30,
    sp1: SP1_TYPES.VAMPIRIC,
    sp2: SP2_TYPES.NORMAL_X3, // TODO
    sp4: SP4_TYPES.ROUGE_150_ALL_STATS,
    runeBuilds: {
      default: {
        runes: ["N", "P", "A"],
        runePrimaries: ["D", "D", "D"],
        runeSecondaries: ["L", "R", "V", "G"],
      },
    },
  },
  {
    name: "Natura",
    elementKind: "earth",
    tribe: "Human",
    sex: "f",
    flying: false,
    crusher: false,
    rarity: RARITY.RARE,
    class: "lancer",
    atk: 34,
    hp: 440,
    def: 12,
    ctkrate: 10,
    ctkdmg: 100,
    aps: 0.4,
    atkrange: 240,
    mvspd: 140,
    effresistance: 8,

    sp1: SP1_TYPES.NORMAL,
    sp2: SP2_TYPES.AOE_300,
    sp4: SP4_TYPES.ELEMENT_DEF_400,
    runeBuilds: {
      default: {
        runes: ["V", "X", "D"],
        runePrimaries: ["A", "A", "A"],
        runeSecondaries: ["L", "D", "V", "R"],
      },
    },
  },
  {
    name: "Tellus",
    elementKind: "earth",
    tribe: "Valken",
    sex: "m",
    flying: false,
    crusher: false,
    rarity: RARITY.RARE,
    class: "brawler",
    atk: 52,
    hp: 480,
    def: 28,
    ctkrate: 15,
    ctkdmg: 100,
    aps: 0.67,
    atkrange: 180,
    mvspd: 100,
    effresistance: 15,
    sp1: SP1_TYPES.NORMAL,
    sp2: SP2_TYPES.NORMAL_X3,
    sp4: SP4_TYPES.ELEMENT_DEF_400,
    sp5: SP5_TYPES.TELLUS_BLOCK_DMG,
    runeBuilds: {
      default: {
        runes: ["V", "A", "D"],
        runePrimaries: ["D", "D", "D"],
        runeSecondaries: ["L", "R", "V", "G"],
      },
    },
  },
  {
    name: "Krouki",
    elementKind: "earth",
    tribe: "Monki",
    sex: "m",
    flying: false,
    crusher: false,
    rarity: RARITY.RARE,
    class: "gunner",
    atk: 38,
    hp: 280,
    def: 10,
    ctkrate: 10,
    ctkdmg: 100,
    aps: 0.83,
    atkrange: 490,
    mvspd: 160,
    effresistance: 10,
    sp1: SP1_TYPES.NORMAL,
    sp2: SP2_TYPES.NORMAL_X3,
    sp4: SP4_TYPES.ELEMENT_CRT_DMG_200,
    runeBuilds: {
      default: {
        runes: ["D", "P", "R"],
        runePrimaries: ["A", "D", "D"],
        runeSecondaries: ["L", "R", "V", "G"],
      },
    },
  },
  {
    name: "Misty",
    elementKind: "earth",
    tribe: "Human",
    sex: "f",
    flying: false,
    crusher: false,
    rarity: RARITY.RARE,
    class: "gunner",
    atk: 20,
    hp: 280,
    def: 8,
    ctkrate: 15,
    ctkdmg: 100,
    aps: 0.83,
    atkrange: 395,
    mvspd: 150,
    effresistance: 12,
    sp1: SP1_TYPES.POISON_30_PRC_5SEC_100_AOE,
    sp2: SP2_TYPES.POISON_30_PRC_5SEC_150_AOE,
    sp4: SP4_TYPES.ELEMENT_ATK_400,
    runeBuilds: {
      default: {
        runes: ["D", "Y", "E"],
        runePrimaries: ["A", "D", "D"],
        runeSecondaries: ["L", "R", "V", "G"],
      },
    },
  },
  {
    name: "Wolfie",
    elementKind: "earth",
    tribe: "Viking",
    sex: "m",
    flying: false,
    crusher: false,
    rarity: RARITY.RARE,
    class: "barbarian",
    atk: 35,
    hp: 600,
    def: 16,
    ctkrate: 20,
    ctkdmg: 100,
    aps: 0.83,
    atkrange: 220,
    mvspd: 130,
    effresistance: 10,
    sp1: SP1_TYPES.NORMAL,
    sp2: SP2_TYPES.AOE_150_X3,
    sp4: SP4_TYPES.ELEMENT_ATK_400,
    runeBuilds: {
      default: {
        runes: ["V", "N", "G"],
        runePrimaries: ["V", "V", "V"],
        runeSecondaries: ["M", "G", "D", "R"],
      },
    },
  },
  {
    name: "Hooky",
    elementKind: "earth",
    tribe: "Viking",
    sex: "m",
    flying: false,
    crusher: false,
    rarity: RARITY.EPIC,
    class: "gunner",
    atk: 30,
    hp: 420,
    def: 20,
    ctkrate: 10,
    ctkdmg: 100,
    aps: 0.83,
    atkrange: 450,
    mvspd: 125,
    effresistance: 10,
    sp1: SP1_TYPES.NORMAL,
    sp2: SP2_TYPES.AOE_150,
    sp4: SP4_TYPES.ELEMENT_ATACK_RANGE_3_PRC,
    sp5: SP5_TYPES.ANTI_PUSHBACK,
    runeBuilds: {
      default: {
        runes: ["A", "D", "E"],
        runePrimaries: ["A", "A", "A"],
        runeSecondaries: ["L", "D", "R", "V"],
      },
    },
  },
  {
    name: "Clawdette",
    elementKind: "earth",
    tribe: "Human",
    sex: "f",
    flying: false,
    crusher: false,
    rarity: RARITY.EPIC,
    class: "brawler",
    atk: 45,
    hp: 410,
    def: 18,
    ctkrate: 20,
    ctkdmg: 100,
    aps: 1,
    atkrange: 160,
    mvspd: 145,
    effresistance: 26,
    sp1: SP1_TYPES.POISON_10_PRC_5SEC,
    sp2: SP2_TYPES.POISON_20_PRC_5SEC,
    sp4: SP4_TYPES.POISON_DMG_50_PRC,
    runeBuilds: {
      default: {
        runes: ["D", "Y", "W"],
        runePrimaries: ["A", "A", "A"],
        runeSecondaries: ["L", "D", "V", "R"],
      },
    },
  },
  {
    name: "Thorn",
    elementKind: "earth",
    tribe: "Voodoo",
    sex: "f",
    flying: false,
    crusher: false,
    rarity: RARITY.EPIC,
    class: "magician",
    atk: 40,
    hp: 400,
    def: 6,
    ctkrate: 15,
    ctkdmg: 100,
    aps: 1,
    atkrange: 500,
    mvspd: 160,
    effresistance: 20,
    sp1: SP1_TYPES.POISON_10_PRC_5SEC,
    sp2: SP2_TYPES.POISON_100_PRC_600_AOE,
    sp4: SP4_TYPES.DEBUF_ELEMENT_DMG_200,
    runeBuilds: {
      default: {
        runes: ["D", "W", "E"],
        runePrimaries: ["A", "E", "E"],
        runeSecondaries: ["L", "R", "V", "G"],
      },
    },
  },
  {
    name: "Green Faery",
    elementKind: "earth",
    tribe: "Human",
    sex: "f",
    flying: true,
    crusher: false,
    rarity: RARITY.EPIC,
    class: "support",
    atk: 20,
    hp: 250,
    def: 14,
    ctkrate: 20,
    ctkdmg: 100,
    aps: 0.5,
    atkrange: 460,
    mvspd: 150,
    effresistance: 29,
    sp1: SP1_TYPES.NORMAL,
    sp2: SP2_TYPES.SHIELD_5_PRC_OF_HEALTH,
    sp4: SP4_TYPES.ALL_HP_400,
    runeBuilds: {
      default: {
        runes: ["V", "N", "X"],
        runePrimaries: ["V", "V", "V"],
        runeSecondaries: ["L", "D", "R", "G"],
      },
    },
    timedSp2Sec: 8,
  },
  {
    name: "Petunia",
    elementKind: "earth",
    tribe: "Human",
    sex: "f",
    flying: false,
    crusher: false,
    rarity: RARITY.EPIC,
    class: "magician",
    atk: 45,
    hp: 300,
    def: 16,
    ctkrate: 20,
    ctkdmg: 100,
    aps: 0.5,
    atkrange: 405,
    mvspd: 180,
    effresistance: 19,
    sp1: SP1_TYPES.NORMAL,
    sp2: SP2_TYPES.FROGIFY,
    sp4: SP4_TYPES.ALL_DEF_500,
    runeBuilds: {
      default: {
        runes: ["D", "P", "R"],
        runePrimaries: ["A", "D", "D"],
        runeSecondaries: ["L", "R", "V", "G"],
      },
    },
    timedSp2Sec: 6,
  },
  {
    name: "Leaf Blade",
    elementKind: "earth",
    tribe: "Human",
    sex: "m",
    flying: false,
    crusher: false,
    rarity: RARITY.EPIC,
    class: "knight",
    atk: 50,
    hp: 370,
    def: 16,
    ctkrate: 15,
    ctkdmg: 100,
    aps: 1,
    atkrange: 150,
    mvspd: 140,
    effresistance: 11,
    sp1: SP1_TYPES.NORMAL,
    sp2: SP2_TYPES.NORMAL_X3,
    sp4: SP4_TYPES.ALL_DEF_400,
    sp5: SP5_TYPES.LAST_HOPE,
    runeBuilds: {
      default: {
        runes: ["V", "K", "N"],
        runePrimaries: ["V", "V", "V"],
        runeSecondaries: ["M", "G", "D", "R"],
      },
    },
  },
  {
    name: "Big Eye",
    elementKind: "light",
    tribe: "Dragon",
    sex: "m",
    flying: true,
    crusher: false,
    rarity: RARITY.COMMON,
    class: "magician",
    atk: 25,
    hp: 450,
    def: 8,
    ctkrate: 10,
    ctkdmg: 100,
    aps: 1,
    atkrange: 310,
    mvspd: 180,
    effresistance: 26,
    sp1: SP1_TYPES.NORMAL,
    sp2: SP2_TYPES.NORMAL_X3,
    runeBuilds: {
      default: {
        runes: ["D", "P", "R"],
        runePrimaries: ["A", "D", "D"],
        runeSecondaries: ["L", "R", "V", "G"],
      },
    },
  },
  {
    name: "Healer Bot",
    elementKind: "light",
    tribe: "Robot",
    sex: "f",
    flying: true,
    crusher: false,
    rarity: RARITY.COMMON,
    class: "support",
    atk: 10,
    hp: 300,
    def: 2,
    ctkrate: 10,
    ctkdmg: 100,
    aps: 1,
    atkrange: 490,
    mvspd: 140,
    effresistance: 25,
    sp1: SP1_TYPES.NORMAL,
    sp2: SP2_TYPES.HEALING_6_PRC_OF_CASTERS_LIFE_FOR_5_SEC,
    runeBuilds: {
      default: {
        runes: ["V", "A", "N"],
        runePrimaries: ["V", "V", "V"],
        runeSecondaries: ["L", "D", "R", "G"],
      },
    },
  },
  {
    name: "Swift",
    elementKind: "light",
    tribe: "Human",
    sex: "f",
    flying: false,
    crusher: false,
    rarity: RARITY.COMMON,
    class: "ranger",
    atk: 24,
    hp: 250,
    def: 10,
    ctkrate: 5,
    ctkdmg: 100,
    aps: 1.25,
    atkrange: 380,
    mvspd: 160,
    effresistance: 6,
    sp1: SP1_TYPES.NORMAL,
    sp2: SP2_TYPES.NORMAL_X3,
    runeBuilds: {
      default: {
        runes: ["D", "P", "R"],
        runePrimaries: ["D", "D", "D"],
        runeSecondaries: ["L", "R", "V", "G"],
      },
    },
  },
  {
    name: "Spike",
    elementKind: "light",
    tribe: "Human",
    sex: "m",
    flying: false,
    crusher: false,
    rarity: RARITY.COMMON,
    class: "barbarian",
    atk: 26,
    hp: 580,
    def: 30,
    ctkrate: 25,
    ctkdmg: 100,
    aps: 0.83,
    atkrange: 200,
    mvspd: 140,
    effresistance: 14,
    sp1: SP1_TYPES.STUN_10_PRC_2_SEC,
    sp2: SP2_TYPES.STUN_30_PRC_350_AOE,
    runeBuilds: {
      default: {
        runes: ["V", "N", "G"],
        runePrimaries: ["V", "V", "V"],
        runeSecondaries: ["M", "G", "D", "R"],
      },
    },
  },
  {
    name: "Light Knight",
    elementKind: "light",
    tribe: "Human",
    sex: "m",
    flying: false,
    crusher: false,
    rarity: RARITY.COMMON,
    class: "rogue",
    atk: 25,
    hp: 350,
    def: 15,
    ctkrate: 20,
    ctkdmg: 100,
    aps: 1,
    atkrange: 120,
    mvspd: 220,
    effresistance: 12,
    dodgerate: 10,
    sp1: SP1_TYPES.NORMAL,
    sp2: SP2_TYPES.NORMAL_X3,
    runeBuilds: {
      default: {
        runes: ["V", "N", "G"],
        runePrimaries: ["V", "V", "V"],
        runeSecondaries: ["M", "G", "D", "R"],
      },
    },
  },
  {
    name: "Bun Gun",
    elementKind: "light",
    tribe: "Vulcan",
    sex: "f",
    flying: false,
    crusher: false,
    rarity: RARITY.RARE,
    class: "gunner",
    atk: 22,
    hp: 270,
    def: 10,
    ctkrate: 10,
    ctkdmg: 100,
    aps: 0.83,
    atkrange: 420,
    mvspd: 150,
    effresistance: 15,
    sp1: SP1_TYPES.AOE_100,
    sp2: SP2_TYPES.BLIND_70_PRC_150_AOE_3_SEC,
    sp4: SP4_TYPES.ELEMENT_2_PRC_DODGE,
    runeBuilds: {
      default: {
        runes: ["A", "X", "E"],
        runePrimaries: ["A", "A", "E"],
        runeSecondaries: ["L", "R", "D", "V"],
      },
    },
  },
  {
    name: "Gold Knight",
    elementKind: "light",
    tribe: "Human",
    sex: "m",
    flying: false,
    crusher: false,
    rarity: RARITY.RARE,
    class: "knight",
    atk: 40,
    hp: 480,
    def: 15,
    ctkrate: 10,
    ctkdmg: 100,
    aps: 1,
    atkrange: 150,
    mvspd: 140,
    effresistance: 12,
    sp1: SP1_TYPES.NORMAL,
    sp2: SP2_TYPES.NORMAL_X3,
    sp4: SP4_TYPES.ELEMENT_MOVE_SPEED_25,
    runeBuilds: {
      default: {
        runes: ["V", "N", "G"],
        runePrimaries: ["V", "V", "V"],
        runeSecondaries: ["M", "G", "D", "R"],
      },
    },
  },
  {
    name: "Arcana",
    elementKind: "light",
    tribe: "Human",
    sex: "f",
    flying: false,
    crusher: false,
    rarity: RARITY.RARE,
    class: "ranger",
    atk: 30,
    hp: 320,
    def: 15,
    ctkrate: 20,
    ctkdmg: 100,
    aps: 1,
    atkrange: 540,
    mvspd: 150,
    effresistance: 12,
    sp1: SP1_TYPES.NORMAL,
    sp2: SP2_TYPES.NORMAL_X3,
    sp4: SP4_TYPES.ELEMENT_CRT_DMG_200,
    runeBuilds: {
      default: {
        runes: ["D", "P", "A"],
        runePrimaries: ["D", "D", "D"],
        runeSecondaries: ["L", "R", "V", "G"],
      },
    },
  },
  {
    name: "Merlinus",
    elementKind: "light",
    tribe: "Human",
    sex: "m",
    flying: false,
    crusher: false,
    rarity: RARITY.RARE,
    class: "support",
    atk: 14,
    hp: 270,
    def: 12,
    ctkrate: 10,
    ctkdmg: 100,
    aps: 0.67,
    atkrange: 550,
    mvspd: 100,
    effresistance: 29,
    sp1: SP1_TYPES.NORMAL,
    sp2: SP2_TYPES.HEAL_100_PRC_CASTER_LIFE,
    sp4: SP4_TYPES.ELEMENT_HP_500,
    runeBuilds: {
      default: {
        runes: ["V", "A", "N"],
        runePrimaries: ["V", "V", "V"],
        runeSecondaries: ["L", "D", "R", "G"],
      },
    },
  },
  {
    name: "Ser Shu",
    elementKind: "light",
    tribe: "Vulcan",
    sex: "f",
    flying: false,
    crusher: false,
    rarity: RARITY.RARE,
    class: "lancer",
    atk: 30,
    hp: 430,
    def: 32,
    ctkrate: 10,
    ctkdmg: 100,
    aps: 0.71,
    atkrange: 340,
    mvspd: 140,
    effresistance: 12,

    sp1: SP1_TYPES.NORMAL,
    sp2: SP2_TYPES.STUN_2_SEC_ATK_DOWN_10_PRC_400_AOE,
    sp4: SP4_TYPES.LANCER_3_PRC_RANGE,
    runeBuilds: {
      default: {
        runes: ["V", "S", "D"],
        runePrimaries: ["A", "A", "A"],
        runeSecondaries: ["L", "D", "V", "R"],
      },
    },
  },
  {
    name: "Joan Of Arc",
    elementKind: "light",
    tribe: "Human",
    sex: "f",
    flying: false,
    crusher: false,
    rarity: RARITY.RARE,
    class: "lancer",
    atk: 28,
    hp: 500,
    def: 12,
    ctkrate: 10,
    ctkdmg: 100,
    aps: 0.4,
    atkrange: 220,
    mvspd: 140,
    effresistance: 12,

    sp1: SP1_TYPES.NORMAL,
    sp2: SP2_TYPES.NORMAL_X3,
    sp4: SP4_TYPES.ELEMENT_DEF_400,
    runeBuilds: {
      default: {
        runes: ["V", "X", "D"],
        runePrimaries: ["A", "A", "A"],
        runeSecondaries: ["L", "D", "V", "R"],
      },
    },
  },
  {
    name: "Ra",
    elementKind: "light",
    tribe: "Human",
    sex: "m",
    flying: false,
    crusher: false,
    rarity: RARITY.RARE,
    class: "magician",
    atk: 38,
    hp: 190,
    def: 15,
    ctkrate: 10,
    ctkdmg: 100,
    aps: 0.67,
    atkrange: 350,
    mvspd: 130,
    effresistance: 23,
    sp1: SP1_TYPES.NORMAL,
    sp2: SP2_TYPES.PUSH10,
    sp4: SP4_TYPES.MAGICIANS_150_ALL,
    sp5: SP5_TYPES.SPAWN_MUMMY_ON_DEATH,
    runeBuilds: {
      default: {
        runes: ["D", "P", "R"],
        runePrimaries: ["A", "D", "D"],
        runeSecondaries: ["L", "R", "V", "G"],
      },
    },
  },
  {
    name: "Krunk",
    elementKind: "light",
    tribe: "Viking",
    sex: "m",
    flying: false,
    crusher: false,
    rarity: RARITY.RARE,
    class: "gunner",
    atk: 28,
    hp: 600,
    def: 14,
    ctkrate: 10,
    ctkdmg: 100,
    aps: 0.83,
    atkrange: 410,
    mvspd: 120,
    effresistance: 10,
    sp1: SP1_TYPES.NORMAL,
    sp2: SP2_TYPES.NORMAL_X3,
    sp4: SP4_TYPES.ELEMENT_ATK_400,
    sp5: SP5_TYPES.ANTI_PUSHBACK,
    runeBuilds: {
      default: {
        runes: ["D", "P", "R"],
        runePrimaries: ["A", "D", "D"],
        runeSecondaries: ["L", "R", "V", "G"],
      },
    },
  },
  {
    name: "Siegfried",
    elementKind: "light",
    tribe: "Viking",
    sex: "m",
    flying: false,
    crusher: false,
    rarity: RARITY.RARE,
    class: "barbarian",
    atk: 32,
    hp: 780,
    def: 14,
    ctkrate: 25,
    ctkdmg: 100,
    aps: 0.83,
    atkrange: 200,
    mvspd: 125,
    effresistance: 14,
    sp1: SP1_TYPES.NORMAL,
    sp2: SP2_TYPES.AOE_350,
    sp4: SP4_TYPES.SELF_HP_800,
    runeBuilds: {
      default: {
        runes: ["V", "N", "G"],
        runePrimaries: ["V", "V", "V"],
        runeSecondaries: ["M", "G", "D", "R"],
      },
    },
  },
  {
    name: "One Eye",
    elementKind: "light",
    tribe: "Human",
    sex: "m",
    flying: false,
    crusher: true,
    rarity: RARITY.RARE,
    class: "rogue",
    atk: 32,
    hp: 480,
    def: 8,
    ctkrate: 10,
    ctkdmg: 100,
    aps: 1,
    atkrange: 310,
    mvspd: 220,
    effresistance: 14,
    dodgerate: 10,
    sp1: SP1_TYPES.NORMAL,
    sp2: SP2_TYPES.NORMAL_X3,
    sp4: SP4_TYPES.ELEMENT_ATK_SPD_10,
    sp5: SP5_TYPES.EVADE_GUNNER_BULLETS,
    runeBuilds: {
      default: {
        runes: ["N", "P", "A"],
        runePrimaries: ["D", "D", "D"],
        runeSecondaries: ["L", "R", "V", "G"],
      },
    },
  },
  {
    name: "Thor",
    elementKind: "light",
    tribe: "Viking",
    sex: "m",
    flying: false,
    crusher: false,
    rarity: RARITY.RARE,
    class: "barbarian",
    atk: 48,
    hp: 600,
    def: 14,
    ctkrate: 25,
    ctkdmg: 100,
    aps: 0.5,
    atkrange: 200,
    mvspd: 100,
    effresistance: 16,
    sp1: SP1_TYPES.NORMAL,
    sp2: SP2_TYPES.THOR_RUSH,
    sp4: SP4_TYPES.ELEMENT_ATK_400,
    runeBuilds: {
      default: {
        runes: ["V", "N", "G"],
        runePrimaries: ["V", "V", "V"],
        runeSecondaries: ["M", "G", "D", "R"],
      },
    },
    timedSp2Sec: 10,
  },
  {
    name: "Hikari",
    elementKind: "light",
    tribe: "Human",
    sex: "m",
    flying: false,
    crusher: false,
    rarity: RARITY.EPIC,
    class: "samurai",
    atk: 40,
    hp: 525,
    def: 6,
    ctkrate: 20,
    ctkdmg: 200,
    aps: 1,
    atkrange: 150,
    mvspd: 170,
    effresistance: 12,
    sp1: SP1_TYPES.NORMAL,
    sp2: SP2_TYPES.NORMAL_X3,
    sp4: SP4_TYPES.ALL_MOVE_SPEED_25,
    runeBuilds: {
      default: {
        runes: ["N", "P", "A"],
        runePrimaries: ["D", "D", "D"],
        runeSecondaries: ["L", "R", "V", "G"],
      },
    },
  },
  {
    name: "Tesla",
    elementKind: "light",
    tribe: "Human",
    sex: "f",
    flying: false,
    crusher: false,
    rarity: RARITY.EPIC,
    class: "magician",
    atk: 36,
    hp: 360,
    def: 6,
    ctkrate: 20,
    ctkdmg: 100,
    aps: 0.83,
    atkrange: 390,
    mvspd: 160,
    effresistance: 19,
    sp1: SP1_TYPES.STUN_20_PRC_CHANCE_3_SEC,
    sp2: SP2_TYPES.STUN_3_SEC_150_AOE,
    sp4: SP4_TYPES.SELF_ATK_800,
    runeBuilds: {
      default: {
        runes: ["D", "P", "E"],
        runePrimaries: ["A", "E", "D"],
        runeSecondaries: ["L", "R", "V", "G"],
      },
    },
  },
  {
    name: "Paladin",
    elementKind: "light",
    tribe: "Human",
    sex: "m",
    flying: false,
    crusher: false,
    rarity: RARITY.EPIC,
    class: "knight",
    atk: 35,
    hp: 550,
    def: 40,
    ctkrate: 10,
    ctkdmg: 100,
    aps: 1,
    atkrange: 150,
    mvspd: 140,
    effresistance: 12,
    sp1: SP1_TYPES.NORMAL,
    sp2: SP2_TYPES.ANGEL_BARRIER,
    sp4: SP4_TYPES.DEBUFF_EFFECT_DURATION_MINUS_25_PRC,
    runeBuilds: {
      default: {
        runes: ["V", "N", "G"],
        runePrimaries: ["V", "V", "V"],
        runeSecondaries: ["L", "G", "D", "R"],
      },
    },
    timedSp2Sec: 20,
  },
  {
    name: "Monki Roboti",
    elementKind: "light",
    tribe: "Monki",
    sex: "m",
    flying: false,
    crusher: false,
    rarity: RARITY.EPIC,
    class: "brawler",
    atk: 50,
    hp: 450,
    def: 20,
    ctkrate: 10,
    ctkdmg: 100,
    aps: 0.77,
    atkrange: 130,
    mvspd: 150,
    effresistance: 25,
    sp1: SP1_TYPES.NORMAL,
    sp2: SP2_TYPES.AOE_300,
    sp4: SP4_TYPES.ALL_ATK_400,
    runeBuilds: {
      default: {
        runes: ["D", "E", "P"],
        runePrimaries: ["A", "E", "D"],
        runeSecondaries: ["L", "R", "V", "G"],
      },
    },
  },
  /* {
      "name": "Angelica",
      "elementKind": "light",
      "tribe": "Human",
      "sex": "f",
      "flying": true,
      "crusher": false,
      "rarity": "legendary",
      "class": "support",
      "atk": 14,
      "hp": 500,
      "def": 20,
      "ctkrate": 0,
      "ctkdmg": 100,
      "aps": 0.33,
      "atkrange": 650,
      "mvspd": 100,
      "effresistance": 35
    }, */
  {
    name: "Skeleton Infantry",
    elementKind: "dark",
    tribe: "Undead",
    sex: "m",
    flying: false,
    crusher: false,
    rarity: RARITY.COMMON,
    class: "rogue",
    atk: 30,
    hp: 300,
    def: 6,
    ctkrate: 10,
    ctkdmg: 100,
    aps: 1,
    atkrange: 160,
    mvspd: 200,
    effresistance: 10,
    dodgerate: 10,
    sp1: SP1_TYPES.NORMAL,
    sp2: SP2_TYPES.NORMAL_X3,
    runeBuilds: {
      default: {
        runes: ["N", "P", "A"],
        runePrimaries: ["D", "D", "D"],
        runeSecondaries: ["L", "R", "V", "G"],
      },
    },
  },
  {
    name: "Skeleton Giant",
    elementKind: "dark",
    tribe: "Undead",
    sex: "m",
    flying: false,
    crusher: false,
    rarity: RARITY.COMMON,
    class: "barbarian",
    atk: 45,
    hp: 380,
    def: 20,
    ctkrate: 15,
    ctkdmg: 100,
    aps: 0.5,
    atkrange: 220,
    mvspd: 100,
    effresistance: 10,
    sp1: SP1_TYPES.NORMAL,
    sp2: SP2_TYPES.AOE_350,
    runeBuilds: {
      default: {
        runes: ["V", "E", "P"],
        runePrimaries: ["A", "E", "V"],
        runeSecondaries: ["L", "V", "R", "G"],
      },
    },
  },
  {
    name: "Skeleton Ranger",
    elementKind: "dark",
    tribe: "Undead",
    sex: "m",
    flying: false,
    crusher: false,
    rarity: RARITY.COMMON,
    class: "ranger",
    atk: 30,
    hp: 200,
    def: 6,
    ctkrate: 10,
    ctkdmg: 100,
    aps: 1,
    atkrange: 455,
    mvspd: 160,
    effresistance: 10,
    sp1: SP1_TYPES.NORMAL,
    sp2: SP2_TYPES.NORMAL_X3,
    runeBuilds: {
      default: {
        runes: ["D", "P", "R"],
        runePrimaries: ["A", "D", "D"],
        runeSecondaries: ["L", "R", "V", "G"],
      },
    },
  },
  {
    name: "Bat",
    elementKind: "dark",
    tribe: "Dragon",
    sex: "m",
    flying: true,
    crusher: false,
    rarity: RARITY.COMMON,
    class: "magician",
    atk: 52,
    hp: 220,
    def: 8,
    ctkrate: 15,
    ctkdmg: 100,
    aps: 1,
    atkrange: 350,
    mvspd: 250,
    effresistance: 18,
    sp1: SP1_TYPES.NORMAL,
    sp2: SP2_TYPES.NORMAL_X3,
    runeBuilds: {
      default: {
        runes: ["D", "P", "R"],
        runePrimaries: ["A", "D", "D"],
        runeSecondaries: ["L", "R", "V", "G"],
      },
    },
  },
  {
    name: "Dragon Bot",
    elementKind: "dark",
    tribe: "Robot",
    sex: "m",
    flying: true,
    crusher: false,
    rarity: RARITY.COMMON,
    class: "gunner",
    atk: 44,
    hp: 280,
    def: 12,
    ctkrate: 15,
    ctkdmg: 100,
    aps: 1,
    atkrange: 430,
    mvspd: 150,
    effresistance: 25,
    sp1: SP1_TYPES.NORMAL,
    sp2: SP2_TYPES.ATK_DOWN_20_PRC_5_SEC,
    runeBuilds: {
      default: {
        runes: ["D", "P", "R"],
        runePrimaries: ["A", "D", "D"],
        runeSecondaries: ["L", "R", "V", "G"],
      },
    },
  },
  {
    name: "Dark Wolf",
    elementKind: "dark",
    tribe: "Viking",
    sex: "m",
    flying: false,
    crusher: false,
    rarity: RARITY.RARE,
    class: "magician",
    atk: 45,
    hp: 400,
    def: 10,
    ctkrate: 10,
    ctkdmg: 100,
    aps: 0.56,
    atkrange: 535,
    mvspd: 100,
    effresistance: 22,
    sp1: SP1_TYPES.NORMAL,
    sp2: SP2_TYPES.NORMAL_X3,
    sp4: SP4_TYPES.DEBUFF_MOVE_SPD_25_PRC,
    runeBuilds: {
      default: {
        runes: ["D", "P", "R"],
        runePrimaries: ["A", "D", "D"],
        runeSecondaries: ["L", "R", "V", "G"],
      },
    },
  },
  {
    name: "Chaos",
    elementKind: "dark",
    tribe: "Undead",
    sex: "m",
    flying: false,
    crusher: false,
    rarity: RARITY.RARE,
    class: "barbarian",
    atk: 80,
    hp: 440,
    def: 20,
    ctkrate: 15,
    ctkdmg: 100,
    aps: 0.5,
    atkrange: 220,
    mvspd: 100,
    effresistance: 12,
    sp1: SP1_TYPES.NORMAL,
    sp2: SP2_TYPES.AOE_150_X3,
    sp4: SP4_TYPES.ELEMENT_DEF_400,
    runeBuilds: {
      default: {
        runes: ["V", "D", "N"],
        runePrimaries: ["V", "V", "V"],
        runeSecondaries: ["L", "M", "D", "G"],
      },
    },
  },
  {
    name: "Neko",
    elementKind: "dark",
    tribe: "Human",
    sex: "f",
    flying: false,
    crusher: false,
    rarity: RARITY.RARE,
    class: "brawler",
    atk: 80,
    hp: 300,
    def: 20,
    ctkrate: 20,
    ctkdmg: 100,
    aps: 1,
    atkrange: 150,
    mvspd: 180,
    effresistance: 18,
    sp1: SP1_TYPES.NORMAL,
    sp2: SP2_TYPES.NORMAL_X3,
    sp4: SP4_TYPES.ELEMENT_MOVE_SPEED_25,
    runeBuilds: {
      default: {
        runes: ["N", "D", "A"],
        runePrimaries: ["D", "D", "D"],
        runeSecondaries: ["L", "R", "V", "G"],
      },
    },
  },
  {
    name: "Monki Mortar",
    elementKind: "dark",
    tribe: "Monki",
    sex: "m",
    flying: false,
    crusher: false,
    rarity: RARITY.RARE,
    class: "gunner",
    atk: 35,
    hp: 230,
    def: 6,
    ctkrate: 10,
    ctkdmg: 100,
    aps: 0.83,
    atkrange: 405,
    mvspd: 170,
    effresistance: 10,
    sp1: SP1_TYPES.AOE_100,
    sp2: SP2_TYPES.AOE_150,
    sp4: SP4_TYPES.ELEMENT_ATK_400,
    runeBuilds: {
      default: {
        runes: ["D", "P", "E"],
        runePrimaries: ["A", "D", "D"],
        runeSecondaries: ["L", "R", "V", "G"],
      },
    },
  },
  {
    name: "Sorrow",
    elementKind: "dark",
    tribe: "Human",
    sex: "f",
    flying: false,
    crusher: true,
    rarity: RARITY.RARE,
    class: "gunner",
    atk: 35,
    hp: 350,
    def: 16,
    ctkrate: 20,
    ctkdmg: 100,
    aps: 0.5,
    atkrange: 620,
    mvspd: 180,
    effresistance: 8,
    sp1: SP1_TYPES.NORMAL,
    sp2: SP2_TYPES.SORROW_FATAL_WEAKNESS,
    sp4: SP4_TYPES.GUNNER_ATK_400,
    runeBuilds: {
      default: {
        runes: ["D", "P", "R"],
        runePrimaries: ["A", "D", "D"],
        runeSecondaries: ["L", "R", "V", "G"],
      },
    },
  },
  {
    name: "Kage",
    elementKind: "dark",
    tribe: "Human",
    sex: "m",
    flying: false,
    crusher: false,
    rarity: RARITY.RARE,
    class: "samurai",
    atk: 75,
    hp: 260,
    def: 6,
    ctkrate: 25,
    ctkdmg: 200,
    aps: 1,
    atkrange: 150,
    mvspd: 170,
    effresistance: 8,
    sp1: SP1_TYPES.NORMAL,
    sp2: SP2_TYPES.NORMAL_X3,
    sp4: SP4_TYPES.DEBUFF_HP_25_PRC,
    runeBuilds: {
      default: {
        runes: ["N", "P", "A"],
        runePrimaries: ["D", "D", "D"],
        runeSecondaries: ["L", "R", "V", "G"],
      },
    },
  },
  {
    name: "Dark Hunter",
    elementKind: "dark",
    tribe: "Human",
    sex: "m",
    flying: false,
    crusher: false,
    rarity: RARITY.RARE,
    class: "ranger",
    atk: 52,
    hp: 200,
    def: 6,
    ctkrate: 24,
    ctkdmg: 100,
    aps: 1,
    atkrange: 590,
    mvspd: 160,
    effresistance: 10,
    sp1: SP1_TYPES.NORMAL,
    sp2: SP2_TYPES.NORMAL_X3,
    sp4: SP4_TYPES.DEBUFF_ATK_50_PRC,
    runeBuilds: {
      default: {
        runes: ["D", "P", "R"],
        runePrimaries: ["A", "D", "D"],
        runeSecondaries: ["L", "R", "V", "G"],
      },
    },
  },
  {
    name: "Circe",
    elementKind: "dark",
    tribe: "Human",
    sex: "f",
    flying: true,
    crusher: false,
    rarity: RARITY.RARE,
    class: "magician",
    atk: 50,
    hp: 250,
    def: 6,
    ctkrate: 10,
    ctkdmg: 100,
    aps: 0.5,
    atkrange: 545,
    mvspd: 160,
    effresistance: 30,
    sp1: SP1_TYPES.NORMAL,
    sp2: SP2_TYPES.CIRCE_POSSESS,
    sp4: SP4_TYPES.ELEMENT_HP_400,
    runeBuilds: {
      default: {
        runes: ["V", "N", "X"],
        runePrimaries: ["A", "A", "A"],
        runeSecondaries: ["L", "V", "D", "R"],
      },
    },
    timedSp2Sec: 6,
  },
  {
    name: "Dark Knight",
    elementKind: "dark",
    tribe: "Human",
    sex: "m",
    flying: false,
    crusher: false,
    rarity: RARITY.RARE,
    class: "knight",
    atk: 70,
    hp: 320,
    def: 15,
    ctkrate: 10,
    ctkdmg: 100,
    aps: 1,
    atkrange: 150,
    mvspd: 120,
    effresistance: 10,
    sp1: SP1_TYPES.NORMAL,
    sp2: SP2_TYPES.NORMAL_X3,
    sp4: SP4_TYPES.DEBUFF_DEF_50_PRC,
    runeBuilds: {
      default: {
        runes: ["V", "K", "N"],
        runePrimaries: ["V", "V", "V"],
        runeSecondaries: ["M", "G", "D", "R"],
      },
    },
  },
  {
    name: "Vlad",
    elementKind: "dark",
    tribe: "Human",
    sex: "m",
    flying: true,
    crusher: false,
    rarity: RARITY.EPIC,
    class: "support",
    atk: 42,
    hp: 250,
    def: 6,
    ctkrate: 10,
    ctkdmg: 100,
    aps: 1,
    atkrange: 560,
    mvspd: 160,
    effresistance: 30,
    sp1: SP1_TYPES.VAMPIRIC,
    sp2: SP2_TYPES.VLAD_BLOOD_LUST,
    sp4: SP4_TYPES.DEBUFF_ATK_SPD_10_PRC,
    runeBuilds: {
      default: {
        runes: ["D", "A", "P"],
        runePrimaries: ["A", "D", "D"],
        runeSecondaries: ["L", "R", "V", "G"],
      },
    },
  },
  {
    name: "Necromancer",
    elementKind: "dark",
    tribe: "Human",
    sex: "m",
    flying: false,
    crusher: false,
    rarity: RARITY.EPIC,
    class: "magician",
    atk: 38,
    hp: 250,
    def: 15,
    ctkrate: 10,
    ctkdmg: 100,
    aps: 0.67,
    atkrange: 605,
    mvspd: 130,
    effresistance: 23,
    sp1: SP1_TYPES.NORMAL,
    sp2: SP2_TYPES.NECROMANCER_SPAWN_SKELETON,
    sp4: SP4_TYPES.SKELETON_BUFF_150_PRC,
    runeBuilds: {
      default: {
        runes: ["V", "X", "D"],
        runePrimaries: ["A", "A", "A"],
        runeSecondaries: ["L", "V", "D", "R"],
      },
    },
    timedSp2Sec: 10,
  },
  {
    name: "Kasumi",
    elementKind: "dark",
    tribe: "Human",
    sex: "f",
    flying: false,
    crusher: false,
    rarity: RARITY.EPIC,
    class: "rogue",
    atk: 38,
    hp: 240,
    def: 8,
    ctkrate: 20,
    ctkdmg: 100,
    aps: 1,
    atkrange: 120,
    mvspd: 220,
    effresistance: 10,
    dodgerate: 10,
    sp1: SP1_TYPES.NORMAL,
    sp2: SP2_TYPES.KASUMI_ASSASINATION,
    sp4: SP4_TYPES.DEBUFF_ATK_SPD_10_PRC,
    runeBuilds: {
      default: {
        runes: ["V", "N", "D"],
        runePrimaries: ["V", "V", "V"],
        runeSecondaries: ["D", "R", "V", "G"],
      },
    },
    timedSp2Sec: 8,
  },
  {
    name: "Trickster",
    elementKind: "dark",
    tribe: "Vulcan",
    sex: "m",
    flying: false,
    crusher: false,
    rarity: RARITY.EPIC,
    class: "magician",
    atk: 48,
    hp: 340,
    def: 10,
    ctkrate: 20,
    ctkdmg: 100,
    aps: 1,
    atkrange: 510,
    mvspd: 200,
    effresistance: 22,
    sp1: SP1_TYPES.TRIKSTER_MAGIC_CARD,
    sp2: SP2_TYPES.TRIKSTER_CARDS_CASCADE,
    sp4: SP4_TYPES.DEBUFF_DURATION_PLUS_6_PRC,
    runeBuilds: {
      default: {
        runes: ["D", "A", "P"],
        runePrimaries: ["A", "D", "D"],
        runeSecondaries: ["L", "R", "V", "G"],
      },
    },
  },
  {
    name: "Onyx",
    elementKind: "dark",
    tribe: "Human",
    sex: "f",
    flying: false,
    crusher: false,
    rarity: RARITY.EPIC,
    class: "lancer",
    atk: 54,
    hp: 300,
    def: 12,
    ctkrate: 10,
    ctkdmg: 100,
    aps: 0.5,
    atkrange: 250,
    mvspd: 150,
    effresistance: 10,

    sp1: SP1_TYPES.NORMAL,
    sp2: SP2_TYPES.AOE_350,
    sp4: SP4_TYPES.ALL_ATK_400,
    runeBuilds: {
      default: {
        runes: ["V", "D", "P"],
        runePrimaries: ["A", "D", "D"],
        runeSecondaries: ["L", "R", "V", "G"],
      },
    },
  } /*}} ,
    {
      "name": "Ornok",
      "elementKind": "dark",
      "tribe": "Viking",
      "sex": "m",
      "flying": false,
      "crusher": false,
      "rarity": "legendary",
      "class": "knight",
      "atk": 64,
      "hp": 500,
      "def": 35,
      "ctkrate": 10,
      "ctkdmg": 100,
      "aps": 0.83,
      "atkrange": 150,
      "mvspd": 110,
      "effresistance": 20
    } */,
];

const serverEmojisIdMap = {
  Trickster: "721314734338736148",
  Vlad: "721314734426685440",
  Sorrow: "721314734850441289",
  LightKnight: "721314735198306305",
  VulcanFighter: "721314449193042040",
  Paladin: "721314735462678649",
  Circe: "721314735093710858",
  Arcana: "721314735387181078",
  SkeletonRanger: "721314734330085398",
  Krunk: "721314735441576000",
  SkeletonInfantry: "721314734258782299",
  VoodooDagger: "721314735529787472",
  Swift: "721314735487975485",
  MonkiMortar: "721314734531543083",
  Tellus: "721314735370534973",
  OneEye: "721314735496364094",
  VulcanArcher: "721314449394237481",
  DarkKnight: "721314734799978559",
  Xak: "721314449247436800",
  Tesla: "721314735294906408",
  Neko: "721314734586200126",
  Wolfie: "721314734896578601",
  Bat: "721314735076933702",
  GoldKnight: "721314735580250132",
  DarkWolf: "721314735110488064",
  Kage: "721314734921613312",
  MonkiRoboti: "721314735324397629",
  BunGun: "721314735303295036",
  DragonBot: "721314734678474793",
  SkeletonGiant: "721314734703509524",
  Necromancer: "721314734850441238",
  BlueFish: "721314449314807888",
  Siegfried: "721314736242950248",
  Pinky: "721314449214013755",
  DarkHunter: "721314735286386739",
  RobinHood: "721314735269740616",
  SerShu: "721314734972076065",
  Magmus: "721314449222533201",
  Onyx: "721314734900641852",
  HealerBot: "721314735257026560",
  Thorn: "721314735315746847",
  Atlantus: "721314449591369749",
  Spike: "721314737463492639",
  Torch: "721314449205493800",
  Pumpking: "721314450644402206",
  Chaos: "721314735244705823",
  BigEye: "721314735370534922",
  Goddess: "721314450891735061",
  BugonautFighter: "721314448911892541",
  Sprout: "721314735357952100",
  TinyDragon: "721314448446324758",
  GreenFaery: "721314450270847027",
  LeafBlade: "721314450480824380",
  JoanOfArc: "721314735433318473",
  Akwa: "721314448152723476",
  Luka: "721314448962224178",
  Petunia: "721314449469734962",
  Jasmine: "721314449453219850",
  Thor: "721314735160819742",
  Hooky: "721314449440636958",
  Ra: "721314736012132392",
  Spark: "721314448761159721",
  Hikari: "721314735143780413",
  Mizu: "721314449348362250",
  Natura: "721314450497601536",
  Pirato: "721314450388287497",
  Namida: "721314449297899540",
  Alda: "721314450367447100",
  Kasumi: "721314734758035458",
  BugonautArcher: "721314449612472330",
  Krouki: "721314448991715399",
  Kasai: "721314449264214040",
  Snowman: "721314450254069790",
  VoodooArcher: "721314735294906451",
  Scud: "721314449528455190",
  Spyro: "721314448417095712",
  Gladiator: "721314449302093915",
  Misty: "721314449176133635",
  VoodooSpear: "721314735370403890",
  BugonautGiant: "721314449478254624",
  Valkyrie: "721314449012555788",
  Groovine: "721314449319002122",
  IceKnight: "721314448983195659",
  BugonautSpear: "721314449260150875",
  Rufus: "721314449037983828",
  Oceana: "721314450854117376",
  FrostQueen: "721314449587306506",
  VulcanHammer: "721314450631819296",
  FireMonk: "721314449868193872",
  Furiosa: "721314450099011616",
  Merlinus: "721314735269609492",
  BlackBeard: "721314450069782600",
  Clawdette: "721314449016750172",
  Musashi: "721314449041915946",
  MechaValken: "721314449411276890",
  IceCube: "721314449390043137",
  MonkiKing: "721314449935302706",
};
const HEROS_ARENA_TIRES = {
  S: [
    "Namida",
    "Valkyrie",
    "Alda",
    "Scud",
    "Leaf Blade",
    "Thorn",
    "Paladin",
    "Tesla",
    "Dark Hunter",
    // 'Ornok',
    "Trickster",
    "Vlad",
  ],
  A: [
    "Akwa",
    "Atlantus",
    "Frost Queen",
    "Monki King",
    "Xak",
    "Gladiator",
    "Misty",
    "Bun Gun",
    "Monki Roboti",
    "Ser Shu",
    "Siegfried",
    "Kage",
    "Kasumi",
    "Monki Mortar",
    "Onyx",
    "Sorrow",
  ],
  B: [
    "Ice Cube",
    "Pirato",
    "Snowman",
    "Furiosa",
    "Magmus",
    "Spark",
    "Torch",
    "Clawdette",
    "Petunia",
    "Pumpking",
    "Wolfie",
    "One Eye",
    "Spike",
    "Thor",
    "Chaos",
    "Dragon Bot",
    "Skeleton Giant",
  ],
  C: [
    "Black Beard",
    "Ice Knight",
    "Rufus",
    "Jasmine",
    "Kasai",
    "Mecha Valken",
    "Spyro",
    "Groovine",
    "Hooky",
    "Krouki",
    "Robin Hood",
    "Tellus",
    "Arcana",
    "Krunk",
    "Merlinus",
    "Healer Bot",
    "Ra",
    "Bat",
    "Circe",
    "Dark Knight",
    "Dark Wolf",
  ],
};

const uniqShortNames = [];

const getHeroShortName = (name) => {
  let shortName = name.split(" ").join("").toLocaleLowerCase();
  if (name.includes(" ")) {
    const parts = name.split(" ");
    const firstLettersShortName = parts
      .map((p) => p[0])
      .join("")
      .toLocaleLowerCase();
    if (!uniqShortNames.includes(firstLettersShortName)) {
      shortName = firstLettersShortName;
    }
  } else if (name.length > 5) {
    const first4lettersShortName = name.slice(0, 4).toLocaleLowerCase();
    if (!uniqShortNames.includes(first4lettersShortName)) {
      shortName = first4lettersShortName;
    }
  }

  uniqShortNames.push(shortName);
  return shortName;
};

const ALL_HEROS /* : Hero[] */ = grimore.map((hg) => {
  const heroName = hg.name;
  const emojiKey = heroName.split(" ").join("");
  const shortName = getHeroShortName(heroName);
  const tire =
    Object.keys(HEROS_ARENA_TIRES).find((tire) =>
      HEROS_ARENA_TIRES[tire].includes(heroName)
    ) || "none";

  return {
    ...hg,
    nameNoSpace: emojiKey,
    shortName,
    emoji: `<:${emojiKey}:${serverEmojisIdMap[emojiKey]}>`,
    emojiId: serverEmojisIdMap[emojiKey],
    tire,
    dodgerate: hg.dodgerate || 0,
    sp4: hg.sp4 || "",
    sp5: hg.sp5 || "",
    runeBuilds: hg.runeBuilds,
    atk: hg.atk / hg.aps
  };
});

const HEROS_BY_NAME = ALL_HEROS.reduce((a, h) => {
  a[h.name] = h;
  return a;
}, {});

const EVENT_HEROS_NAMES /* :EventHeroName[] */ = [
  "Ice Knight",
  "Snowman",
  "Pinky",
  "Pumpking",
  "Ra",
  "Circe",
  "Trickster",
  "Ser Shu",
  "Bun Gun",
];

const BLITZ_SHOP_HERO_NAMES /* :BlitzShopHeroName[] */ = ["Thor"];

const CRUSHER_HEROS_NAMES /* :CrusherHeroName[] */ = [
  "Atlantus",
  "Furiosa",
  "Groovine",
  "One Eye",
  "Sorrow",
];
const BLITZ_HERO_NAMES /* :BlitzHeroName[] */ = [
  "Paladin",
  "Vlad",
  "Hooky",
  "Frost Queen",
  "Clawdette",
  "Necromancer",
  "Namida",
];

/* ::

type FcRotation = {|
  common: CommonHeroName[],
  rare: FcRareHeroName[],
  epic: FcEpicHeroName[],
|}
*/

const COMMON_HERO_NAMES /* :CommonHeroName[] */ = [
  "Bugonaut Archer",
  "Bat",
  "Blue Fish",
  "Light Knight",
  "Skeleton Giant",
  "Vulcan Archer",
  "Skeleton Infantry",
  "Spike",
  "Big Eye",
  "Sprout",
  "Swift",
  "Vulcan Fighter",
  "Bugonaut Spear",
  "Dragon Bot",
  "Voodoo Dagger",
  "Skeleton Ranger",
  "Bugonaut Fighter",
  "Voodoo Archer",
  "Bugonaut Giant",
  "Tiny Dragon",
  "Voodoo Spear",
  "Vulcan Hammer",
  "Healer Bot",
];

const FC_RARE_HERO_NAMES /* :FcRareHeroName[] */ = [
  "Akwa",
  "Dark Hunter",
  "Gladiator",
  "Tellus",
  "Musashi",
  "Robin Hood",
  "Goddess",
  "Black Beard",
  "Luka",
  "Mizu",
  "Oceana",
  "Fire Monk",
  "Siegfried",
  "Natura",
  "Mecha Valken",
  "Kasai",
  "Pirato",
  "Joan Of Arc",
  "Krouki",
  "Dark Knight",
  "Krunk",
  "Wolfie",
  "Monki Mortar",
  "Misty",
  "Neko",
  "Xak",
  "Spyro",
  "Dark Wolf",
  "Gold Knight",
  "Chaos",
  "Jasmine",
  "Arcana",
  "Merlinus",
  "Rufus",
  "Magmus",
  "Kage",
  "Spark",
];

const FC_EPIC_HERO_NAMES /* :FcEpicHeroName[] */ = [
  "Leaf Blade",
  "Hikari",
  "Onyx",
  "Green Faery",
  "Petunia",
  "Ice Cube",
  "Alda",
  "Scud",
  "Tesla",
  "Valkyrie",
  "Torch",
  "Kasumi",
  "Thorn",
];

const FC_ROTATION /* :FcRotation */ = {
  common: COMMON_HERO_NAMES,
  rare: FC_RARE_HERO_NAMES,
  epic: FC_EPIC_HERO_NAMES,
};

const FALL_BACK_HERO = ALL_HEROS[0];
const findHeroDefenitionByName = (heroName /* :HeroName */) => {
  const hero = ALL_HEROS.find((h) => h.name === heroName);

  if (!hero) {
    return ALL_HEROS[0];
  }
  return hero;
};
const getEmojiByHeroName = (heroName /* :HeroName */) => {
  const hero = findHeroDefenitionByName(heroName);

  return hero.emoji;
};

export {
  FC_ROTATION,
  BLITZ_HERO_NAMES,
  ALL_HEROS,
  EVENT_HEROS_NAMES,
  BLITZ_SHOP_HERO_NAMES,
  CRUSHER_HEROS_NAMES,
  COMMON_HERO_NAMES,
  FC_RARE_HERO_NAMES,
  FC_EPIC_HERO_NAMES,
  FALL_BACK_HERO,
  findHeroDefenitionByName,
  getEmojiByHeroName,
  HEROS_ARENA_TIRES,
  HEROS_BY_NAME,
};
